// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw4GAQ3623CqfZ43dcM2ck0Goq6gg41e8',
    appId: '1:584167776701:web:023fc60ffd7bf92bdd72d4',
    messagingSenderId: '584167776701',
    projectId: 'farmconnect-4a45b',
    authDomain: 'farmconnect-4a45b.firebaseapp.com',
    storageBucket: 'farmconnect-4a45b.appspot.com',
    measurementId: 'G-53M87J3BTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-MqiXVGBZY35oK0WXzNtuHPNenZEmb_E',
    appId: '1:584167776701:android:303c4554de77b835dd72d4',
    messagingSenderId: '584167776701',
    projectId: 'farmconnect-4a45b',
    storageBucket: 'farmconnect-4a45b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFBW7kdjhBVxHYiHj6EJTYXdUf9fGy1cI',
    appId: '1:584167776701:ios:02b28a9251964b12dd72d4',
    messagingSenderId: '584167776701',
    projectId: 'farmconnect-4a45b',
    storageBucket: 'farmconnect-4a45b.appspot.com',
    iosBundleId: 'com.example.farmconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFBW7kdjhBVxHYiHj6EJTYXdUf9fGy1cI',
    appId: '1:584167776701:ios:02b28a9251964b12dd72d4',
    messagingSenderId: '584167776701',
    projectId: 'farmconnect-4a45b',
    storageBucket: 'farmconnect-4a45b.appspot.com',
    iosBundleId: 'com.example.farmconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw4GAQ3623CqfZ43dcM2ck0Goq6gg41e8',
    appId: '1:584167776701:web:d23bc7463e9bbce4dd72d4',
    messagingSenderId: '584167776701',
    projectId: 'farmconnect-4a45b',
    authDomain: 'farmconnect-4a45b.firebaseapp.com',
    storageBucket: 'farmconnect-4a45b.appspot.com',
    measurementId: 'G-NVHX5HCGTS',
  );
}
